#!/bin/sh
set -e

filesToFormat="$(git --no-pager diff --name-status | awk '$1 != "D" && $2 ~ /\.kts|\.java|\.kt/ { print $2}')"

echo "files to format $filesToFormat"
for sourceFilePath in $filesToFormat
do
  ./gradlew spotlessApply -PspotlessIdeHook="$(pwd)/$sourceFilePath"
  git add $sourceFilePath
done;
